const ERROR_TOKEN_MISSING = "ERROR_TOKEN_MISSING";
const ERROR_INVALID_TOKEN = "ERROR_INVALID_TOKEN";
const ERROR_INTERNAL_SERVER_ERROR = "ERROR_INTERNAL_SERVER_ERROR";
const ERROR_INVALID_FIELD = "ERROR_INVALID_FIELD";
const ERROR_FIELDS_MISSING = "ERROR_FIELDS_MISSING";
const ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_EXISTS";
const ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL";
const ERROR_INVALID_NAME = "ERROR_INVALID_NAME";
const ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD";
const ERROR_INVALID_LASTNAME = "ERROR_INVALID_LASTNAME";
const ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING =
  "ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING";
const ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING =
  "ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING";
const ERROR_INVALID_EMAIL_OR_PASSWORD = "ERROR_INVALID_EMAIL_OR_PASSWORD";
const ERROR_OCCUPATION_INVALID = "ERROR_OCCUPATION_INVALID"
const ERROR_NO_SUCH_USER_FOUND = "ERROR_NO_SUCH_USER_FOUND";
const ERROR_INVALID_START_DATE = "ERROR_INVALID_START_DATE";
const ERROR_INVALID_STOP_DATE = "ERROR_INVALID_STOP_DATE";

exports.ERRORS = {
  ERROR_TOKEN_MISSING,
  ERROR_INVALID_TOKEN,
  ERROR_INTERNAL_SERVER_ERROR,
  ERROR_INVALID_FIELD,
  ERROR_EMAIL_ALREADY_IN_USE,
  ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING,
  ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING,
  ERROR_INVALID_EMAIL_OR_PASSWORD,
  ERROR_NO_SUCH_USER_FOUND,
  ERROR_INVALID_EMAIL,
  ERROR_INVALID_NAME,
  ERROR_INVALID_PASSWORD,
  ERROR_INVALID_LASTNAME,
  ERROR_FIELDS_MISSING,
  ERROR_INVALID_START_DATE,
  ERROR_INVALID_STOP_DATE,
  ERROR_OCCUPATION_INVALID
};
